services:
  dbactividad:
    image: mysql
    restart: always
    volumes:
      - ./dbs/base_actividad:/var/lib/mysql
    container_name: dbactividad
    hostname: dbactividad
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_DATABASE: actividad
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Admin
    ports:
      - "33000:3306"
    networks:
      my-network:
        aliases:
          - dbactividad
  
  dbsedes:
    image: mysql
    restart: always
    volumes:
      - ./dbs/base_sedes:/var/lib/mysql
    container_name: dbsedes
    hostname: dbsedes
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_DATABASE: sedes
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Admin
    ports:
      - "33001:3306"
    networks:
      my-network:
        aliases:
          - dbsedes
  
  dbeventos:
    image: mysql
    restart: always
    volumes:
      - ./dbs/base_eventos:/var/lib/mysql
    container_name: dbeventos
    hostname: dbeventos
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_DATABASE: eventos
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Admin
    ports:
      - "33002:3306"
    networks:
      my-network:
        aliases:
          - dbeventos
  
  dbadmin:
    image: mysql
    restart: always
    volumes:
      - ./dbs/base_admin:/var/lib/mysql
    container_name: dbadmin
    hostname: dbadmin
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_DATABASE: admin
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Admin
    ports:
      - "33003:3306"
    networks:
      my-network:
        aliases:
          - dbadmin
  
  dbusuario:
    image: mysql
    restart: always
    volumes:
      - ./dbs/base_usuario:/var/lib/mysql
    container_name: dbusuario
    hostname: dbusuario
    environment:
      MYSQL_ROOT_PASSWORD: Admin
      MYSQL_DATABASE: usuario
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Admin
    ports:
      - "33004:3306"
    networks:
      my-network:
        aliases:
          - dbusuario

  eureka:
    build:
      context: ./eureka
      dockerfile: eureka.dockerfile
    container_name: eureka
    hostname: eureka
    ports:
      - "8761:8761"
    networks:
      my-network:
        aliases:
          - eureka

  configserver:
    build:
      context: ./configserver
      dockerfile: config.dockerfile
    container_name: configserver
    hostname: configserver
    depends_on:
      - eureka
    ports:
      - "8888:8888"
    networks:
      my-network:
        aliases:
          - configserver
    environment:
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
  
  servicioactividad:
    build:
      context: ./servicioactividad
      dockerfile: actividad.dockerfile
    container_name: servicioactividad
    hostname: servicioactividad
    depends_on:
      - eureka
      - configserver
    ports:
      - "8084:8080"
    networks:
      my-network:
        aliases:
          - servicioactividad
    environment:
      CONFIG_SERVER_URL: http://configserver:8888
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
      DB_URL: dbactividad:3306
      DB_NOMBRE: actividad
      DB_USUARIO: Admin
      DB_CONTRASENA: Admin
  
  servicioadmin:
    build:
      context: ./servicioadmin
      dockerfile: admin.dockerfile
    container_name: servicioadmin
    hostname: servicioadmin
    depends_on:
      - eureka
      - configserver
    ports:
      - "8083:8080"
    networks:
      my-network:
        aliases:
          - servicioadmin
    environment:
      CONFIG_SERVER_URL: http://configserver:8888
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
      DB_URL: dbadmin:3306
      DB_NOMBRE: admin
      DB_USUARIO: Admin
      DB_CONTRASENA: Admin
  
  servicioeventos:
    build:
      context: ./servicioeventos
      dockerfile: evento.dockerfile
    container_name: servicioeventos
    hostname: servicioeventos
    depends_on:
      - eureka
      - configserver
    ports:
      - "8082:8080"
    networks:
      my-network:
        aliases:
          - servicioeventos
    environment:
      CONFIG_SERVER_URL: http://configserver:8888
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
      DB_URL: dbeventos:3306
      DB_NOMBRE: eventos
      DB_USUARIO: Admin
      DB_CONTRASENA: Admin
  
  serviciosedes:
    build:
      context: ./serviciosedes
      dockerfile: sedes.dockerfile
    container_name: serviciosedes
    hostname: serviciosedes
    depends_on:
      - eureka
      - configserver
    ports:
      - "8085:8080"
    networks:
      my-network:
        aliases:
          - serviciosedes
    environment:
      CONFIG_SERVER_URL: http://configserver:8888
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
      DB_URL: dbsedes:3306
      DB_NOMBRE: sedes
      DB_USUARIO: Admin
      DB_CONTRASENA: Admin
  
  serviciousuario:
    build:
      context: ./serviciousuario
      dockerfile: usuario.dockerfile
    container_name: serviciousuario
    hostname: serviciousuario
    depends_on:
      - eureka
      - configserver
    ports:
      - "8081:8080"
    networks:
      my-network:
        aliases:
          - serviciousuario
    environment:
      CONFIG_SERVER_URL: http://configserver:8888
      EUREKA_SERVER_URL: http://eureka:8761/eureka/
      DB_URL: dbusuario:3306
      DB_NOMBRE: usuario
      DB_USUARIO: Admin
      DB_CONTRASENA: Admin
    

networks:
  my-network:

