server:
  port: 8095

spring:
  application:
    name: reporte-microservice
  cloud:
    discovery:
      enabled: true
    feign:
      discovery:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/realms/ecommerce/protocol/openid-connect/certs
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true