server:
  port: 3306
spring:
  datasource:
    url: jdbc:mysql://${DB_URL:localhost:3306}/${DB_NOMBRE:tu_base_de_datos}
    username: ${DB_USUARIO:tu_usuario}
    password: ${DB_CONTRASENA:tu_contraseña}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update